In [2]:
import open3d as o3d


In [3]:
filename = "/home/nero/Documents/person and road for semantic analysis - Cloud2.ply"

point_cloud = o3d.io.read_point_cloud(filename)

o3d.visualization.draw_geometries([point_cloud])

In [5]:
import numpy as np

pcd_array = np.asarray(point_cloud.points)

In [6]:
import pandas as pd

pcd_df = pd.DataFrame(pcd_array)

In [7]:
pcd_df.head()

0        1         2
0 -2.44912  7.66455  0.280984
1 -2.40729  7.69508  0.281560
2  7.16648 -8.06078  0.376651
3  7.10137 -8.08621  0.375811
4  7.13555 -8.22570  0.380266

In [33]:
from surface_variation import PointCloudAnalysis

In [12]:
pcd_object = PointCloudAnalysis(point_cloud.points)

In [13]:
pcd_object.compute_surface_variation()

array([5.04199672e-03, 5.04199672e-03, 2.87850496e-02, ...,
       4.97490964e-14, 4.97490169e-14, 4.97494791e-14])

In [14]:
normalized_surf_var = pcd_object.get_normalized_surface_variation()

In [15]:
normalized_planarity = pcd_object.get_normalized_planarity()

In [17]:
len(point_cloud.points)

29573

In [18]:
len(normalized_surf_var)

29573

In [22]:
pcd_object.display_surface_variation()

In [21]:
pcd_object.display_planarity()

In [25]:
kdtree.get_search_type()

<Type.KNNSearch: 0>

In [7]:
from surface_variation import PointCloudAnalysis

kdtreeseachknn = o3d.geometry.KDTreeSearchParamKNN(50)

pcd_object = PointCloudAnalysis(point_cloud.points, kdtreeseachknn)

In [ ]:
pcd_object.display_surface_variation(threshold=0.2)

In [6]:
pcd_object.display_planarity()

In [7]:
import numpy as np

# Create a sample array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Set elements to zero if they are less than a threshold
threshold = 5
arr[arr < threshold] = 0

print("Array after thresholding:")
print(arr)


Array after thresholding:
[[0 0 0]
 [0 5 6]
 [7 8 9]]


In [8]:
arr< threshold

array([[ True,  True,  True],
       [ True, False, False],
       [False, False, False]])

In [10]:
arr[arr<threshold] = 0

In [11]:
arr

array([[0, 0, 0],
       [0, 5, 6],
       [7, 8, 9]])

In [12]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [ ]:
arr[]

### Understanding geo3dfeatures library

In [1]:
%matplotlib inline

In [3]:
from pathlib import Path

In [4]:


import matplotlib
from matplotlib import pyplot as plt
import pandas as pd
import seaborn as sns



In [5]:
plt.style.use("seaborn-notebook")

In [11]:
from geo3dfeatures.io import read_las, read_ply
from geo3dfeatures.extract import process_full
from geo3dfeatures.extract import compute_tree, request_tree, extract


In [12]:
filename = "geo3dfeatures/sample_data/input/pcd_person_with_road.ply"

In [15]:
rawdata = read_ply(filename)
rawdata = pd.DataFrame(rawdata, columns=list("xyz"))

In [17]:
print(rawdata.shape)
rawdata.head()

(29573, 3)


x        y         z
0 -2.44912  7.66455  0.280984
1 -2.40729  7.69508  0.281560
2  7.16648 -8.06078  0.376651
3  7.10137 -8.08621  0.375811
4  7.13555 -8.22570  0.380266

In [18]:


LEAF_SIZE = 1_000
N_NEIGHBORS = 10



In [19]:
COORDS = list("xyz")
tree = compute_tree(rawdata[COORDS].values, leaf_size=LEAF_SIZE)

In [20]:
random_point = rawdata[COORDS].sample()

In [21]:
random_point

x        y        z
13699  5.9509  4.07372 -2.40167

In [24]:
distance, neighbors_index = request_tree(random_point.values, tree, N_NEIGHBORS)

In [25]:
distance, neighbors_index = distance.squeeze(), neighbors_index.squeeze()
print("distance: ", distance)
print("index: ", neighbors_index)

distance:  [0.         0.04395609 0.04396274 0.08790253 0.08791561 0.13183897
 0.13187756 0.17472172 0.17575667 0.1758007  0.18004085]
index:  [13699 13700 13698 13701 13697 13702 13696 14648 13703 13695 14647]


In [27]:
rawdata.loc[neighbors_index] # random point and 10 neighbors of the random point

x        y        z
13699  5.95090  4.07372 -2.40167
13700  5.97563  4.03738 -2.40167
13698  5.92594  4.10991 -2.40167
13701  6.00012  4.00089 -2.40167
13697  5.90078  4.14595 -2.40167
13702  6.02437  3.96425 -2.40167
13696  5.87539  4.18184 -2.40167
14648  5.80672  3.97503 -2.40167
13703  6.04836  3.92746 -2.40167
13695  5.84984  4.21757 -2.40167
14647  5.78238  4.01035 -2.40167

In [28]:
pd.Series(distance).describe()

count    11.000000
mean      0.112161
std       0.063601
min       0.000000
25%       0.065933
50%       0.131839
75%       0.175239
max       0.180041
dtype: float64

In [29]:
VOISINS_NUM = [10, 20, 30, 50, 100, 200, 500, 1000, 1500, 2000]

In [ ]:
print("Vegetation neighborhood sizes:")
veg_sample = vegetation[COORDS].sample(20).values
gen = (request_tree(veg_sample, tree, num) for num in VOISINS_NUM)
d = [{"mean (in meter)": d.mean(axis=1)[0], "max (in meter)": d.max(axis=1)[0]} for d, _ in gen]
pd.DataFrame(d, index=VOISINS_NUM).T

In [31]:
rawdata_sample = rawdata[COORDS].sample(20).values
rawdata_sample

array([[-6.02922 ,  4.60331 , -2.40167 ],
       [-4.44117 ,  6.90842 , -1.94358 ],
       [-0.947812, -5.55077 , -2.40168 ],
       [ 5.53031 , -7.04109 , -2.40169 ],
       [-7.16039 ,  6.34651 , -1.67181 ],
       [-0.583789,  5.37554 , -2.40167 ],
       [ 8.02969 , -0.122349, -2.34711 ],
       [-5.04598 ,  2.75486 , -2.40168 ],
       [ 2.31758 , -7.65317 , -2.40169 ],
       [ 3.38047 ,  4.95444 , -2.40167 ],
       [-1.5923  ,  8.68567 , -2.29858 ],
       [-6.69438 , -0.449429, -2.40168 ],
       [-3.9435  ,  7.04338 , -1.97371 ],
       [ 1.12305 , -6.45869 , -2.40169 ],
       [ 4.72637 , -7.92398 , -2.40169 ],
       [-4.14031 ,  6.98965 , -1.66947 ],
       [ 5.64703 , -7.65903 , -2.40169 ],
       [ 1.98906 , -7.74504 , -2.40169 ],
       [-0.157031, -6.86794 , -2.40169 ],
       [-7.94844 ,  6.70628 , -2.29858 ]], dtype=float32)

In [32]:
gen = (request_tree(rawdata_sample, tree, num) for num in VOISINS_NUM)
gen

<generator object <genexpr> at 0x7fbf504af3c0>

In [33]:
d = [{"mean (in meter)": d.mean(axis=1)[0], "max (in meter)": d.max(axis=1)[0]} for d, _ in gen]
pd.DataFrame(d, index=VOISINS_NUM).T

10        20        30        50        100       200   \
mean (in meter)  0.119312  0.164267  0.194895  0.255366  0.358176  0.505280   
max (in meter)   0.196605  0.231145  0.277381  0.384613  0.550407  0.748931   

                     500       1000      1500      2000  
mean (in meter)  0.795266  1.115619  1.349242  1.536558  
max (in meter)   1.186270  1.648347  1.980517  2.211082

In [35]:
rawdata_store = pd.HDFStore("geo3dfeatures/sample_data/output/pcd_person_with_road/features/features.h5", "r")

[09:26:14] utils._init_num_threads (INFO) - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[09:26:14] utils._init_num_threads (INFO) - NumExpr defaulting to 8 threads.


In [37]:
rawdata_store

<class 'pandas.io.pytables.HDFStore'>
File path: geo3dfeatures/sample_data/output/pcd_person_with_road/features/features.h5

In [39]:
VOISINS_NUM = [10, 20, 30, 50, 100, 200, 500, 1000, 1500, 2000]

KEYS = {i: "/num_{:04d}".format(i) for i in VOISINS_NUM}
KEYS

{10: '/num_0010',
 20: '/num_0020',
 30: '/num_0030',
 50: '/num_0050',
 100: '/num_0100',
 200: '/num_0200',
 500: '/num_0500',
 1000: '/num_1000',
 1500: '/num_1500',
 2000: '/num_2000'}

In [ ]:
def mean_features(store, feature_name):
    result = pd.Series({num: store["/num_{:04d}".format(num)][feature_name].mean() for num in VOISINS_NUM})
    result.name = feature_name
    return result

In [40]:
pd.DataFrame(rawdata_store)

0
0  /num_0050
1  /num_0200

In [41]:
rawdata_store["/num_0050"]

x         y         z  num_neighbors     alpha      beta  \
0    -2.44912  7.664550  0.280984             50  0.971752  0.021410   
1    -2.40729  7.695080  0.281560             50  0.971752  0.021410   
2     7.16648 -8.060780  0.376651             50  0.536871  0.401570   
3     7.10137 -8.086210  0.375811             50  0.536871  0.401570   
4     7.13555 -8.225700  0.380266             50  0.536871  0.401570   
...       ...       ...       ...            ...       ...       ...   
9568 -5.19533 -0.158345 -2.401680             50  0.594002  0.405998   
9569 -5.19619 -0.126680 -2.401680             50  0.593998  0.406002   
9570 -5.19689 -0.095015 -2.401680             50  0.594000  0.406000   
9571 -5.19736 -0.063345 -2.401680             50  0.593998  0.406002   
9572 -5.19766 -0.031670 -2.401680             50  0.593996  0.406004   

        radius   z_range   std_dev    density  ...  planarity  scattering  \
0     2.177029  1.144363  0.337702   1.203157  ...   0.010871    0.002315   
1     2.181001  1.144363  0.337702   1.196596  ...   0.010871    0.002315   
2     2.853738  0.806283  0.232403   0.534162  ...   0.264827    0.027064   
3     2.849642  0.806283  0.232403   0.536468  ...   0.264827    0.027064   
4     2.866770  0.806283  0.232403   0.526910  ...   0.264827    0.027064   
...        ...       ...       ...        ...  ...        ...         ...   
9568  0.644102  0.000000  0.000000  46.456914  ...   0.254704    0.000000   
9569  0.644081  0.000000  0.000000  46.461515  ...   0.254707    0.000000   
9570  0.644090  0.000000  0.000000  46.459503  ...   0.254705    0.000000   
9571  0.644101  0.000000  0.000000  46.457094  ...   0.254706    0.000000   
9572  0.644081  0.000000  0.000000  46.461546  ...   0.254709    0.000000   

      omnivariance  anisotropy  eigenentropy  eigenvalue_sum  radius_2D  \
0         0.030774    0.997685      0.085417        5.912795   0.078253   
1         0.030774    0.997685      0.085417        5.912795   0.108088   
2         0.151000    0.972936      0.623415        3.726998   0.521982   
3         0.151000    0.972936      0.623415        3.726998   0.501851   
4         0.151000    0.972936      0.623415        3.726998   0.359121   
...            ...         ...           ...             ...        ...   
9568      0.000000    1.000000      0.504532        1.710846   0.305737   
9569      0.000000    1.000000      0.504535        1.710847   0.305750   
9570      0.000000    1.000000      0.504534        1.710838   0.305743   
9571      0.000000    1.000000      0.504534        1.710843   0.305740   
9572      0.000000    1.000000      0.504536        1.710856   0.305740   

       density_2D  eigenvalue_sum_2D  eigenvalue_ratio_2D  
0     2703.013097           0.096625             0.162086  
1     1416.756108           0.096625             0.162086  
2       60.749394           0.972426             0.086494  
3       65.721001           0.972426             0.086494  
4      128.342788           0.972426             0.086494  
...           ...                ...                  ...  
9568   177.075527           1.710846             0.254704  
9569   177.060355           1.710847             0.254707  
9570   177.068317           1.710838             0.254705  
9571   177.071085           1.710843             0.254706  
9572   177.071669           1.710856             0.254709  

[29573 rows x 23 columns]

In [42]:
rawdata_store["/num_0050"].columns

Index(['x', 'y', 'z', 'num_neighbors', 'alpha', 'beta', 'radius', 'z_range',
       'std_dev', 'density', 'verticality', 'curvature_change', 'linearity',
       'planarity', 'scattering', 'omnivariance', 'anisotropy', 'eigenentropy',
       'eigenvalue_sum', 'radius_2D', 'density_2D', 'eigenvalue_sum_2D',
       'eigenvalue_ratio_2D'],
      dtype='object')

In [3]:
!ls csv

actor_ObjIdx_0.0.csv	actor_ObjIdx_416.0.csv	actor_ObjIdx_439.0.csv
actor_ObjIdx_413.0.csv	actor_ObjIdx_417.0.csv	actor_ObjIdx_442.0.csv
actor_ObjIdx_414.0.csv	actor_ObjIdx_418.0.csv	actor_ObjIdx_580.0.csv
actor_ObjIdx_415.0.csv	actor_ObjIdx_430.0.csv


In [ ]:
import pandas as pd

filename = "csv/actor_ObjIdx_0.0.csv"

df_idx0 = pd.read_csv(filename, )